apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
    # usage of port 80 allows to use urls to specific services without indicating of ports in clients-kube.properties
    - port: 80
      targetPort: 8080
  type: LoadBalancer
