server:
  port: 8080
spring:
  application:
    # The name used by EUREKA
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/customer
    username: horkovcode
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
