server:
  port: 8080
spring:
  application:
    # The name used by EUREKA
    name: customer
  datasource:
    password: 'password'
    # connection through url while this microservice is not docker container
    url: jdbc:postgresql://postgres:5432/customer
    username: 'horkovcode'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
