services:
# The Database container
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: horkovcode
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

#grafical UI client for Postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # Zipkin Container configuration
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - "9411:9411"
  # Zipkin Container configuration
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      # The port used by microservices in order to publish messages
      - "5672:5672"
      # Management port to use management console
      - "15672:15672"
#network communication
networks:
  postgres:
    driver: bridge

#Volumes to store data
volumes:
  postgres:
  pgadmin:
