services:
  # The Database container
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: horkovcode
      POSTGRES_PASSWORD: 'password'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  # graphical UI client for Postgres
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  # Zipkin Container configuration
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
    - "9411:9411"
    networks:
      - spring
  # rabbitmq Container configuration
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      # The port used by microservices in order to publish messages
      - "5672:5672"
      # Management port to use management console
      - "15672:15672"
    networks:
      - spring
  # Configuration of eureka server
#  eureka-server:
#    image: nickl0gist/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
  # Configuration of apigw
#  apigw:
#    image: nickl0gist/apigw:latest
#    container_name: apigw
#    ports:
#      - "8083:8083"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
  # Configuration of customer
  customer:
    image: nickl0gist/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      #- eureka-server
      - postgres
      - rabbitmq
  # Configuration of fraud
  fraud:
    image: nickl0gist/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      #- eureka-server
      - postgres
      - rabbitmq
  # Configuration of notification
  notification:
    image: nickl0gist/notification:latest
    container_name: notification
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      #- eureka-server
      - postgres
      - rabbitmq
# network communication
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

# Volumes to store data
volumes:
  postgres:
  pgadmin:
