server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    password: 'password'
    # connection through url while this microservice is not docker container
    url: jdbc:postgresql://postgres:5432/notification
    username: 'horkovcode'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbitmq:5672
# Properties for how to connect to Queue including the exchange and routing key.
rabbitmq:
  # Topic exchange
  exchanges:
    internal: internal.exchange
  # Queue setting
  queue:
    notification: notification.queue
  # Binding of the Topic Exchange to Queue
  routing-keys:
    internal-notification: internal.notification.routing-key
