server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          # name of Application in Eureka server
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        # - id: fraud
        # name of Application in Eureka server
        #    uri: lb://FRAUD
        #    predicates:
        #      - Path=/api/v1/fraud/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
